### ISSUE TITLE
Not working the clara-cpp

### ISSUE THREAD

**Issue by whit2333** [JeffersonLab/clara-java#10]
See the issue in the clara-demo project, 
https://github.com/JeffersonLab/clara-demo/issues/3  

I believe last year I did not have this problem. 

```
2019-06-28 13:09:51.972: Could not use 172.17.0.1 for processing:
could not start container = 172.17.0.1%7150_cpp:whit
```
What does this mean?

**Comment by smancill** [comment]
Should be fixed by JeffersonLab/xmsg-cpp@93dfd68dad14d9d45863b7cf1d2a4894ae02283e.

C++ issues should go in https://github.com/JeffersonLab/clara-cpp/issues.
